version: "2"

services:
  mysqldb:
    image: mysql:latest 
    ports: 
      - "3306:3306"
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=1
      - MYSQL_DATABASE=hobbie_backend_db

  spring-backend:
    image: spring-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8880:8888"
    environment:
      - spring.datasource.url=jdbc:mysql://172.31.3.141:3306/hobbie_backend_db?useSSL=false
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

networks:
  springmysql-net:
